# Generated by Django 3.1.2 on 2020-10-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordOperations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('para_text', models.CharField(max_length=200, verbose_name='要操作的段落内容')),
                ('char_edit_op', models.BooleanField(verbose_name='是否考查文字查找替换？')),
                ('char_edit_origin', models.CharField(max_length=200, verbose_name='原词')),
                ('char_edit_replace', models.CharField(max_length=200, verbose_name='替换为')),
                ('font_op', models.BooleanField(verbose_name='是否考查字体设置？')),
                ('font_name_ascii', models.CharField(choices=[('无', '无'), ('MS Gothic', 'MS Gothic'), ('MS Mincho', 'MS Mincho'), ('MS PMincho', 'MS PMincho'), ('MS UI Gothic', 'MS UI Gothic'), ('Yu Gothic', 'Yu Gothic')], max_length=200, verbose_name='英文字体')),
                ('font_name_chinese', models.CharField(choices=[('无', '无'), ('宋体', '宋体'), ('黑体', '黑体'), ('华文仿宋', '华文仿宋')], max_length=200, verbose_name='中文字体')),
                ('font_size', models.CharField(choices=[('一号', '一号'), ('二号', '二号'), ('三号', '三号'), ('四号', '四号'), ('五号', '五号'), ('六号', '六号'), ('七号', '七号'), ('八号', '八号')], max_length=200, verbose_name='字号')),
                ('font_color', models.CharField(choices=[('无', '无'), ('红色', '红色'), ('黄色', '黄色'), ('绿色', '绿色')], max_length=200, verbose_name='字体颜色')),
                ('font_bold', models.BooleanField(verbose_name='粗体')),
                ('font_italic', models.BooleanField(verbose_name='斜体')),
                ('font_underline', models.CharField(choices=[('无', '无'), ('下划线', '下划线'), ('双下划线', '双下划线'), ('粗线', '粗线')], max_length=200, verbose_name='下划线')),
                ('paraformat_op', models.BooleanField(verbose_name='是否考查段落格式设置？')),
                ('para_alignment', models.CharField(choices=[('无', '无'), ('左对齐', '左对齐'), ('居中', '居中'), ('右对齐', '右对齐'), ('两端对齐', '两端对齐'), ('分散对齐', '分散对齐')], max_length=200, verbose_name='段落对齐')),
                ('para_left_indent', models.CharField(max_length=200, verbose_name='左侧缩进(磅)')),
                ('para_right_indent', models.CharField(max_length=200, verbose_name='右侧缩进(磅)')),
                ('para_first_line_indent', models.CharField(choices=[('无', '无'), ('首行', '首行'), ('悬挂', '悬挂')], max_length=200, verbose_name='首行缩进')),
                ('para_first_line_indent_size', models.CharField(max_length=200, verbose_name='首行缩进距离(磅)')),
                ('para_space_before', models.CharField(max_length=200, verbose_name='段前间距(磅)')),
                ('para_space_after', models.CharField(max_length=200, verbose_name='段后间距(磅)')),
                ('para_line_spacing_rule', models.CharField(choices=[('无', '无'), ('单倍行距', '单倍行距'), ('多倍行距', '多倍行距'), ('固定值', '固定值')], max_length=200, verbose_name='行距规则')),
                ('para_line_spacing', models.CharField(max_length=200, verbose_name='行距(行)')),
                ('para_firstchardropcap', models.CharField(choices=[('无', '无'), ('下沉', '下沉'), ('下沉', '悬挂')], max_length=200, verbose_name='首字下沉')),
                ('para_firstchardropcaplines', models.CharField(max_length=200, verbose_name='下沉(行)')),
                ('para_line_page', models.CharField(choices=[('孤行控制', '孤行控制'), ('与下段同页', '与下段同页'), ('段中不分页', '段中不分页'), ('段前分页', '段前分页')], max_length=200, verbose_name='换行和分页')),
            ],
        ),
    ]
