# Generated by Django 3.1.2 on 2020-10-21 10:31

from django.db import migrations, models
import django.db.models.deletion
import polls.fileModels


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordDocxFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(blank=True, null=True, upload_to='uploads_docx/', validators=[polls.fileModels.validate_docx])),
            ],
            options={
                'verbose_name': '考试用Word文件',
                'verbose_name_plural': '考试用Word文件',
            },
        ),
        migrations.CreateModel(
            name='WordDocxFileTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(blank=True, null=True, upload_to='uploads_docx_test/', validators=[polls.fileModels.validate_docx])),
            ],
            options={
                'verbose_name': '内部测试用word文件',
                'verbose_name_plural': '内部测试用word文件',
            },
        ),
        migrations.CreateModel(
            name='WordOperations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='创建时间')),
                ('para_text', models.TextField(verbose_name='要考查的段落内容')),
                ('char_edit_op', models.BooleanField(default=False, verbose_name='是否考查文字查找替换？')),
                ('char_edit_origin', models.CharField(blank=True, max_length=200, verbose_name='原词')),
                ('char_edit_replace', models.CharField(blank=True, max_length=200, verbose_name='替换为')),
                ('font_op', models.BooleanField(default=False, verbose_name='是否考查字体设置？')),
                ('font_name_ascii', models.CharField(blank=True, choices=[('MS Gothic', 'MS Gothic'), ('MS Mincho', 'MS Mincho'), ('Yu Gothic', 'Yu Gothic'), ('Arial Black', 'Arial Black'), ('Bahnschrift', 'Bahnschrift'), ('Book Antiqua', 'Book Antiqua'), ('Calibri', 'Calibri'), ('Dubai', 'Dubai'), ('Impact', 'Impact')], max_length=200, verbose_name='英文字体')),
                ('font_name_chinese', models.CharField(blank=True, choices=[('宋体', '宋体'), ('黑体', '黑体'), ('华文仿宋', '华文仿宋'), ('楷体', '楷体'), ('幼圆', '幼圆'), ('微软雅黑', '微软雅黑'), ('隶书', '隶书')], max_length=200, verbose_name='中文字体')),
                ('font_size', models.CharField(blank=True, choices=[('一号', '一号'), ('小一', '小一'), ('二号', '二号'), ('小二', '小二'), ('三号', '三号'), ('小三', '小三'), ('四号', '四号'), ('小四', '小四'), ('五号', '五号'), ('小五', '小五'), ('六号', '六号'), ('小六', '小六'), ('七号', '七号'), ('小七', '小七'), ('八号', '八号'), ('小八', '小八')], max_length=200, verbose_name='字号')),
                ('font_bold', models.BooleanField(blank=True, verbose_name='粗体')),
                ('font_italic', models.BooleanField(blank=True, verbose_name='斜体')),
                ('font_underline', models.CharField(blank=True, choices=[('下划线', '下划线'), ('双下划线', '双下划线'), ('粗线', '粗线'), ('波浪线', '波浪线'), ('虚线', '虚线')], max_length=200, verbose_name='下划线')),
                ('font_color', models.CharField(blank=True, choices=[('红色', '红色'), ('黄色', '黄色'), ('绿色', '绿色')], max_length=200, verbose_name='字体颜色')),
                ('paraformat_op', models.BooleanField(default=False, verbose_name='是否考查段落格式设置？')),
                ('para_alignment', models.CharField(blank=True, choices=[('左对齐', '左对齐'), ('居中', '居中'), ('右对齐', '右对齐'), ('两端对齐', '两端对齐'), ('分散对齐', '分散对齐')], max_length=200, verbose_name='段落对齐')),
                ('para_left_indent', models.CharField(blank=True, choices=[('5', '5'), ('10', '10'), ('15', '15'), ('20', '20'), ('25', '25'), ('30', '30'), ('35', '35')], max_length=200, verbose_name='左侧缩进(磅)')),
                ('para_right_indent', models.CharField(blank=True, choices=[('5', '5'), ('10', '10'), ('15', '15'), ('20', '20'), ('25', '25'), ('30', '30'), ('35', '35')], max_length=200, verbose_name='右侧缩进(磅)')),
                ('para_first_line_indent', models.CharField(blank=True, choices=[('首行', '首行'), ('悬挂', '悬挂')], max_length=200, verbose_name='首行缩进')),
                ('para_first_line_indent_size', models.CharField(blank=True, choices=[('5', '5'), ('10', '10'), ('15', '15'), ('20', '20'), ('25', '25'), ('30', '30'), ('35', '35')], max_length=200, verbose_name='首行缩进距离(磅)')),
                ('para_space_before', models.CharField(blank=True, choices=[('5', '5'), ('10', '10'), ('15', '15'), ('20', '20'), ('25', '25'), ('30', '30'), ('35', '35')], max_length=200, verbose_name='段前间距(磅)')),
                ('para_space_after', models.CharField(blank=True, choices=[('5', '5'), ('10', '10'), ('15', '15'), ('20', '20'), ('25', '25'), ('30', '30'), ('35', '35')], max_length=200, verbose_name='段后间距(磅)')),
                ('para_line_spacing_rule', models.CharField(blank=True, choices=[('单倍行距', '单倍行距'), ('多倍行距', '多倍行距'), ('固定值', '固定值')], max_length=200, verbose_name='行距规则')),
                ('para_line_spacing', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=200, verbose_name='行距(行)')),
                ('para_firstchardropcap', models.CharField(blank=True, choices=[('下沉', '下沉'), ('下沉', '悬挂')], max_length=200, verbose_name='首字下沉')),
                ('para_firstchardropcaplines', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=200, verbose_name='下沉(行)')),
                ('page_break_before', models.BooleanField(default=False, verbose_name='段前分页')),
                ('keep_with_next', models.BooleanField(default=False, verbose_name='与下段同页')),
                ('keep_together', models.BooleanField(default=False, verbose_name='段中不分页')),
                ('window_control', models.BooleanField(default=False, verbose_name='孤行控制')),
                ('style_op', models.BooleanField(default=False, verbose_name='是否考查样式设置？')),
                ('style_name', models.CharField(blank=True, choices=[('标题1', '标题1'), ('标题2', '标题2'), ('标题3', '标题3'), ('标题4', '标题4'), ('正文', '正文'), ('强调', '强调'), ('列表编号', '列表编号'), ('列表项目符号', '列表项目符号'), ('新样式1', '新样式1'), ('新样式2', '新样式2')], max_length=200, verbose_name='样式名称')),
                ('style_font_name_ascii', models.CharField(blank=True, choices=[('MS Gothic', 'MS Gothic'), ('MS Mincho', 'MS Mincho'), ('Yu Gothic', 'Yu Gothic'), ('Arial Black', 'Arial Black'), ('Bahnschrift', 'Bahnschrift'), ('Book Antiqua', 'Book Antiqua'), ('Calibri', 'Calibri'), ('Dubai', 'Dubai'), ('Impact', 'Impact')], max_length=200, verbose_name='英文字体')),
                ('style_font_name_chinese', models.CharField(blank=True, choices=[('宋体', '宋体'), ('黑体', '黑体'), ('华文仿宋', '华文仿宋'), ('楷体', '楷体'), ('幼圆', '幼圆'), ('微软雅黑', '微软雅黑'), ('隶书', '隶书')], max_length=200, verbose_name='中文字体')),
                ('style_font_size', models.CharField(blank=True, choices=[('一号', '一号'), ('小一', '小一'), ('二号', '二号'), ('小二', '小二'), ('三号', '三号'), ('小三', '小三'), ('四号', '四号'), ('小四', '小四'), ('五号', '五号'), ('小五', '小五'), ('六号', '六号'), ('小六', '小六'), ('七号', '七号'), ('小七', '小七'), ('八号', '八号'), ('小八', '小八')], max_length=200, verbose_name='字号')),
                ('style_font_bold', models.BooleanField(default=False, verbose_name='粗体')),
                ('style_font_italic', models.BooleanField(default=False, verbose_name='斜体')),
                ('style_font_underline', models.CharField(blank=True, choices=[('下划线', '下划线'), ('双下划线', '双下划线'), ('粗线', '粗线'), ('波浪线', '波浪线'), ('虚线', '虚线')], max_length=200, verbose_name='下划线')),
                ('style_font_color', models.CharField(blank=True, choices=[('红色', '红色'), ('黄色', '黄色'), ('绿色', '绿色')], max_length=200, verbose_name='字体颜色')),
                ('style_para_alignment', models.CharField(blank=True, choices=[('左对齐', '左对齐'), ('居中', '居中'), ('右对齐', '右对齐'), ('两端对齐', '两端对齐'), ('分散对齐', '分散对齐')], max_length=200, verbose_name='段落对齐')),
                ('style_para_left_indent', models.CharField(blank=True, choices=[('5', '5'), ('10', '10'), ('15', '15'), ('20', '20'), ('25', '25'), ('30', '30'), ('35', '35')], max_length=200, verbose_name='左侧缩进(磅)')),
                ('style_para_right_indent', models.CharField(blank=True, choices=[('5', '5'), ('10', '10'), ('15', '15'), ('20', '20'), ('25', '25'), ('30', '30'), ('35', '35')], max_length=200, verbose_name='右侧缩进(磅)')),
                ('style_para_first_line_indent', models.CharField(blank=True, choices=[('首行', '首行'), ('悬挂', '悬挂')], max_length=200, verbose_name='首行缩进')),
                ('style_para_first_line_indent_size', models.CharField(blank=True, choices=[('5', '5'), ('10', '10'), ('15', '15'), ('20', '20'), ('25', '25'), ('30', '30'), ('35', '35')], max_length=200, verbose_name='首行缩进距离(磅)')),
                ('style_para_space_before', models.CharField(blank=True, choices=[('5', '5'), ('10', '10'), ('15', '15'), ('20', '20'), ('25', '25'), ('30', '30'), ('35', '35')], max_length=200, verbose_name='段前间距(磅)')),
                ('style_para_space_after', models.CharField(blank=True, choices=[('5', '5'), ('10', '10'), ('15', '15'), ('20', '20'), ('25', '25'), ('30', '30'), ('35', '35')], max_length=200, verbose_name='段后间距(磅)')),
                ('style_para_line_spacing_rule', models.CharField(blank=True, choices=[('单倍行距', '单倍行距'), ('多倍行距', '多倍行距'), ('固定值', '固定值')], max_length=200, verbose_name='行距规则')),
                ('style_para_line_spacing', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=200, verbose_name='行距(行)')),
                ('style_para_firstchardropcap', models.CharField(blank=True, choices=[('下沉', '下沉'), ('下沉', '悬挂')], max_length=200, verbose_name='首字下沉')),
                ('style_para_firstchardropcaplines', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=200, verbose_name='下沉(行)')),
                ('style_page_break_before', models.BooleanField(default=False, verbose_name='段前分页')),
                ('style_keep_with_next', models.BooleanField(default=False, verbose_name='与下段同页')),
                ('style_keep_together', models.BooleanField(default=False, verbose_name='段中不分页')),
                ('style_window_control', models.BooleanField(default=False, verbose_name='孤行控制')),
                ('image_op', models.BooleanField(default=False, verbose_name='是否考查图片插入？')),
                ('image_position_style', models.CharField(blank=True, choices=[('嵌入文本行中', '嵌入文本行中')], max_length=200, verbose_name='位置类型')),
                ('image_width', models.CharField(blank=True, choices=[('5', '5'), ('10', '10'), ('15', '15'), ('20', '20'), ('25', '25'), ('30', '30'), ('35', '35')], max_length=200, verbose_name='图像宽(厘米)')),
                ('image_height', models.CharField(blank=True, choices=[('5', '5'), ('10', '10'), ('15', '15'), ('20', '20'), ('25', '25'), ('30', '30'), ('35', '35')], max_length=200, verbose_name='图像高(厘米)')),
                ('upload_image_file', models.FileField(blank=True, null=True, upload_to='uploads_image/', validators=[polls.fileModels.validate_image], verbose_name='上传图片')),
                ('upload_docx', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.worddocxfile', verbose_name='考试用Word文件(.docx)')),
            ],
            options={
                'verbose_name': 'Word操作',
                'verbose_name_plural': 'Word操作',
            },
        ),
        migrations.CreateModel(
            name='WordQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='创建时间')),
                ('upload_docx', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.worddocxfile', verbose_name='上传Word文件(.docx)')),
                ('upload_docx_test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.worddocxfiletest', verbose_name='内部测试用word文件.docx')),
                ('word_operation_list', models.ManyToManyField(blank=True, help_text='操作对应的Word文件必须和上面的Word文件一致', to='polls.WordOperations', verbose_name='操作题目')),
            ],
            options={
                'verbose_name': 'Word题目',
                'verbose_name_plural': 'Word题目',
            },
        ),
    ]
