# Generated by Django 3.1.2 on 2020-10-25 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordoperations',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='wordoperations',
            name='upload_docx',
        ),
        migrations.RemoveField(
            model_name='wordquestion',
            name='word_operation_list',
        ),
        migrations.AddField(
            model_name='wordoperations',
            name='word_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.wordquestion', verbose_name='word操作大题'),
        ),
    ]
