# Generated by Django 3.1.2 on 2020-11-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wordoperations',
            old_name='style_window_control',
            new_name='style_widow_control',
        ),
        migrations.RenameField(
            model_name='wordoperations',
            old_name='window_control',
            new_name='widow_control',
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='style_name',
            field=models.CharField(blank=True, choices=[('标题1', '标题1'), ('标题2', '标题2'), ('标题3', '标题3'), ('标题4', '标题4'), ('强调', '强调'), ('列表编号', '列表编号'), ('列表项目符号', '列表项目符号'), ('新样式1', '新样式1'), ('新样式2', '新样式2')], default='', max_length=200, verbose_name='样式名称'),
        ),
    ]
