# Generated by Django 3.1.2 on 2020-12-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exampaper',
            name='end_by_hand',
            field=models.BooleanField(verbose_name='是否已经手动结束'),
        ),
    ]
