# Generated by Django 3.1.2 on 2020-10-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordoperations',
            name='keep_together',
            field=models.BooleanField(null=True, verbose_name='段中不分页'),
        ),
        migrations.AddField(
            model_name='wordoperations',
            name='keep_with_next',
            field=models.BooleanField(null=True, verbose_name='与下段同页'),
        ),
        migrations.AddField(
            model_name='wordoperations',
            name='page_break_before',
            field=models.BooleanField(null=True, verbose_name='段前分页'),
        ),
        migrations.AddField(
            model_name='wordoperations',
            name='window_control',
            field=models.BooleanField(null=True, verbose_name='孤行控制'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='para_first_line_indent_size',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='首行缩进距离(磅)'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='para_firstchardropcaplines',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='下沉(行)'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='para_left_indent',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='左侧缩进(磅)'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='para_line_page',
            field=models.BooleanField(null=True, verbose_name='是否考查分页设置？'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='para_line_spacing',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='行距(行)'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='para_right_indent',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='右侧缩进(磅)'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='para_space_after',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='段后间距(磅)'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='para_space_before',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='段前间距(磅)'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='para_text',
            field=models.TextField(max_length=200, verbose_name='要操作的段落内容'),
        ),
    ]
