# Generated by Django 3.1.2 on 2020-12-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20201218_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampaper',
            name='start_time',
            field=models.DateTimeField(default='1000-11-12 12:00', verbose_name='开考时间'),
        ),
    ]
