# Generated by Django 3.1.2 on 2020-11-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20201110_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordoperations',
            name='para_firstchardropcap',
        ),
        migrations.RemoveField(
            model_name='wordoperations',
            name='para_firstchardropcaplines',
        ),
        migrations.RemoveField(
            model_name='wordoperations',
            name='style_para_firstchardropcap',
        ),
        migrations.RemoveField(
            model_name='wordoperations',
            name='style_para_firstchardropcaplines',
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='font_underline',
            field=models.CharField(blank=True, choices=[('True', '普通下划线'), ('DOUBLE (3)', '双下划线'), ('THICK (6)', '粗下划线'), ('WAVY (11)', '波浪下划线')], default='', max_length=200, verbose_name='下划线'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='para_alignment',
            field=models.CharField(blank=True, choices=[('LEFT (0)', '左对齐'), ('CENTER (1)', '居中对齐'), ('RIGHT (2)', '右对齐'), ('JUSTIFY (3)', '两端对齐'), ('DISTRIBUTE (4)', '分散对齐')], default='', max_length=200, verbose_name='段落对齐'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='para_line_spacing',
            field=models.CharField(blank=True, choices=[('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='', max_length=200, verbose_name='行距(行)'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='para_line_spacing_rule',
            field=models.CharField(blank=True, choices=[('SINGLE (0)', '单倍行距'), ('ONE_POINT_FIVE (1)', '1.5倍行距'), ('DOUBLE (2)', '双倍行距'), ('MULTIPLE (5)', '多倍行距')], default='', max_length=200, verbose_name='行距规则'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='style_font_underline',
            field=models.CharField(blank=True, choices=[('True', '普通下划线'), ('DOUBLE (3)', '双下划线'), ('THICK (6)', '粗下划线'), ('WAVY (11)', '波浪下划线')], default='', max_length=200, verbose_name='下划线'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='style_para_alignment',
            field=models.CharField(blank=True, choices=[('LEFT (0)', '左对齐'), ('CENTER (1)', '居中对齐'), ('RIGHT (2)', '右对齐'), ('JUSTIFY (3)', '两端对齐'), ('DISTRIBUTE (4)', '分散对齐')], default='', max_length=200, verbose_name='段落对齐'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='style_para_line_spacing',
            field=models.CharField(blank=True, choices=[('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='', max_length=200, verbose_name='行距(行)'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='style_para_line_spacing_rule',
            field=models.CharField(blank=True, choices=[('SINGLE (0)', '单倍行距'), ('ONE_POINT_FIVE (1)', '1.5倍行距'), ('DOUBLE (2)', '双倍行距'), ('MULTIPLE (5)', '多倍行距')], default='', max_length=200, verbose_name='行距规则'),
        ),
    ]
