# Generated by Django 3.1.2 on 2020-10-27 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20201025_1939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wordoperations',
            options={'verbose_name': 'Word操作列表', 'verbose_name_plural': 'Word操作列表'},
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='char_edit_origin',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='原词'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='char_edit_replace',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='替换为'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='font_bold',
            field=models.BooleanField(blank=True, default='', verbose_name='粗体'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='font_color',
            field=models.CharField(blank=True, choices=[('红色', '红色'), ('黄色', '黄色'), ('绿色', '绿色')], default='', max_length=200, verbose_name='字体颜色'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='font_italic',
            field=models.BooleanField(blank=True, default='', verbose_name='斜体'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='font_name_ascii',
            field=models.CharField(blank=True, choices=[('MS Gothic', 'MS Gothic'), ('MS Mincho', 'MS Mincho'), ('Yu Gothic', 'Yu Gothic'), ('Arial Black', 'Arial Black'), ('Bahnschrift', 'Bahnschrift'), ('Book Antiqua', 'Book Antiqua'), ('Calibri', 'Calibri'), ('Dubai', 'Dubai'), ('Impact', 'Impact')], default='', max_length=200, verbose_name='英文字体'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='font_name_chinese',
            field=models.CharField(blank=True, choices=[('宋体', '宋体'), ('黑体', '黑体'), ('华文仿宋', '华文仿宋'), ('楷体', '楷体'), ('幼圆', '幼圆'), ('微软雅黑', '微软雅黑'), ('隶书', '隶书')], default='', max_length=200, verbose_name='中文字体'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='font_size',
            field=models.CharField(blank=True, choices=[('一号', '一号'), ('小一', '小一'), ('二号', '二号'), ('小二', '小二'), ('三号', '三号'), ('小三', '小三'), ('四号', '四号'), ('小四', '小四'), ('五号', '五号'), ('小五', '小五'), ('六号', '六号'), ('小六', '小六'), ('七号', '七号'), ('小七', '小七'), ('八号', '八号'), ('小八', '小八')], default='', max_length=200, verbose_name='字号'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='font_underline',
            field=models.CharField(blank=True, choices=[('下划线', '下划线'), ('双下划线', '双下划线'), ('粗线下划线', '粗线'), ('波浪线下划线', '波浪线'), ('虚线下划线', '虚线')], default='', max_length=200, verbose_name='下划线'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='image_height',
            field=models.CharField(blank=True, choices=[('5', '5'), ('10', '10'), ('15', '15'), ('20', '20'), ('25', '25'), ('30', '30'), ('35', '35')], default='', max_length=200, verbose_name='图像高(厘米)'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='image_position_style',
            field=models.CharField(choices=[('嵌入文本行中', '嵌入文本行中')], default='嵌入文本行中', max_length=200, verbose_name='位置类型'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='image_width',
            field=models.CharField(blank=True, choices=[('5', '5'), ('10', '10'), ('15', '15'), ('20', '20'), ('25', '25'), ('30', '30'), ('35', '35')], default='', max_length=200, verbose_name='图像宽(厘米)'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='para_alignment',
            field=models.CharField(blank=True, choices=[('左对齐', '左对齐'), ('居中', '居中'), ('右对齐', '右对齐'), ('两端对齐', '两端对齐'), ('分散对齐', '分散对齐')], default='', max_length=200, verbose_name='段落对齐'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='para_first_line_indent',
            field=models.CharField(blank=True, choices=[('首行缩进', '缩进'), ('首行悬挂', '悬挂')], default='', max_length=200, verbose_name='首行缩进'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='para_first_line_indent_size',
            field=models.CharField(blank=True, choices=[('5', '5'), ('10', '10'), ('15', '15'), ('20', '20'), ('25', '25'), ('30', '30'), ('35', '35')], default='', max_length=200, verbose_name='首行缩进距离(磅)'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='para_firstchardropcap',
            field=models.CharField(blank=True, choices=[('下沉', '下沉'), ('悬挂', '悬挂')], default='', max_length=200, verbose_name='首字下沉'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='para_firstchardropcaplines',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='', max_length=200, verbose_name='下沉(行)'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='para_left_indent',
            field=models.CharField(blank=True, choices=[('5', '5'), ('10', '10'), ('15', '15'), ('20', '20'), ('25', '25'), ('30', '30'), ('35', '35')], default='', max_length=200, verbose_name='左侧缩进(磅)'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='para_line_spacing',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='', max_length=200, verbose_name='行距(行)'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='para_line_spacing_rule',
            field=models.CharField(blank=True, choices=[('单倍行距', '单倍行距'), ('多倍行距', '多倍行距'), ('固定值', '固定值')], default='', max_length=200, verbose_name='行距规则'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='para_right_indent',
            field=models.CharField(blank=True, choices=[('5', '5'), ('10', '10'), ('15', '15'), ('20', '20'), ('25', '25'), ('30', '30'), ('35', '35')], default='', max_length=200, verbose_name='右侧缩进(磅)'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='para_space_after',
            field=models.CharField(blank=True, choices=[('5', '5'), ('10', '10'), ('15', '15'), ('20', '20'), ('25', '25'), ('30', '30'), ('35', '35')], default='', max_length=200, verbose_name='段后间距(磅)'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='para_space_before',
            field=models.CharField(blank=True, choices=[('5', '5'), ('10', '10'), ('15', '15'), ('20', '20'), ('25', '25'), ('30', '30'), ('35', '35')], default='', max_length=200, verbose_name='段前间距(磅)'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='style_font_color',
            field=models.CharField(blank=True, choices=[('红色', '红色'), ('黄色', '黄色'), ('绿色', '绿色')], default='', max_length=200, verbose_name='字体颜色'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='style_font_name_ascii',
            field=models.CharField(blank=True, choices=[('MS Gothic', 'MS Gothic'), ('MS Mincho', 'MS Mincho'), ('Yu Gothic', 'Yu Gothic'), ('Arial Black', 'Arial Black'), ('Bahnschrift', 'Bahnschrift'), ('Book Antiqua', 'Book Antiqua'), ('Calibri', 'Calibri'), ('Dubai', 'Dubai'), ('Impact', 'Impact')], default='', max_length=200, verbose_name='英文字体'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='style_font_name_chinese',
            field=models.CharField(blank=True, choices=[('宋体', '宋体'), ('黑体', '黑体'), ('华文仿宋', '华文仿宋'), ('楷体', '楷体'), ('幼圆', '幼圆'), ('微软雅黑', '微软雅黑'), ('隶书', '隶书')], default='', max_length=200, verbose_name='中文字体'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='style_font_size',
            field=models.CharField(blank=True, choices=[('一号', '一号'), ('小一', '小一'), ('二号', '二号'), ('小二', '小二'), ('三号', '三号'), ('小三', '小三'), ('四号', '四号'), ('小四', '小四'), ('五号', '五号'), ('小五', '小五'), ('六号', '六号'), ('小六', '小六'), ('七号', '七号'), ('小七', '小七'), ('八号', '八号'), ('小八', '小八')], default='', max_length=200, verbose_name='字号'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='style_font_underline',
            field=models.CharField(blank=True, choices=[('下划线', '下划线'), ('双下划线', '双下划线'), ('粗线下划线', '粗线'), ('波浪线下划线', '波浪线'), ('虚线下划线', '虚线')], default='', max_length=200, verbose_name='下划线'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='style_name',
            field=models.CharField(blank=True, choices=[('标题1', '标题1'), ('标题2', '标题2'), ('标题3', '标题3'), ('标题4', '标题4'), ('正文', '正文'), ('强调', '强调'), ('列表编号', '列表编号'), ('列表项目符号', '列表项目符号'), ('新样式1', '新样式1'), ('新样式2', '新样式2')], default='', max_length=200, verbose_name='样式名称'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='style_para_alignment',
            field=models.CharField(blank=True, choices=[('左对齐', '左对齐'), ('居中', '居中'), ('右对齐', '右对齐'), ('两端对齐', '两端对齐'), ('分散对齐', '分散对齐')], default='', max_length=200, verbose_name='段落对齐'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='style_para_first_line_indent',
            field=models.CharField(blank=True, choices=[('首行缩进', '缩进'), ('首行悬挂', '悬挂')], default='', max_length=200, verbose_name='首行缩进'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='style_para_first_line_indent_size',
            field=models.CharField(blank=True, choices=[('5', '5'), ('10', '10'), ('15', '15'), ('20', '20'), ('25', '25'), ('30', '30'), ('35', '35')], default='', max_length=200, verbose_name='首行缩进距离(磅)'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='style_para_firstchardropcap',
            field=models.CharField(blank=True, choices=[('下沉', '下沉'), ('悬挂', '悬挂')], default='', max_length=200, verbose_name='首字下沉'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='style_para_firstchardropcaplines',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='', max_length=200, verbose_name='下沉(行)'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='style_para_left_indent',
            field=models.CharField(blank=True, choices=[('5', '5'), ('10', '10'), ('15', '15'), ('20', '20'), ('25', '25'), ('30', '30'), ('35', '35')], default='', max_length=200, verbose_name='左侧缩进(磅)'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='style_para_line_spacing',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='', max_length=200, verbose_name='行距(行)'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='style_para_line_spacing_rule',
            field=models.CharField(blank=True, choices=[('单倍行距', '单倍行距'), ('多倍行距', '多倍行距'), ('固定值', '固定值')], default='', max_length=200, verbose_name='行距规则'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='style_para_right_indent',
            field=models.CharField(blank=True, choices=[('5', '5'), ('10', '10'), ('15', '15'), ('20', '20'), ('25', '25'), ('30', '30'), ('35', '35')], default='', max_length=200, verbose_name='右侧缩进(磅)'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='style_para_space_after',
            field=models.CharField(blank=True, choices=[('5', '5'), ('10', '10'), ('15', '15'), ('20', '20'), ('25', '25'), ('30', '30'), ('35', '35')], default='', max_length=200, verbose_name='段后间距(磅)'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='style_para_space_before',
            field=models.CharField(blank=True, choices=[('5', '5'), ('10', '10'), ('15', '15'), ('20', '20'), ('25', '25'), ('30', '30'), ('35', '35')], default='', max_length=200, verbose_name='段前间距(磅)'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='word_question',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='polls.wordquestion', verbose_name='word操作大题'),
        ),
        migrations.AlterField(
            model_name='wordquestion',
            name='upload_docx_test',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.worddocxfiletest', verbose_name='内部测试用word文件.docx'),
        ),
    ]
