# Generated by Django 3.1.2 on 2020-12-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_exampaper_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampaper',
            name='current_choice_question_id',
            field=models.PositiveIntegerField(default=0, verbose_name='当前选择题'),
        ),
    ]
