# Generated by Django 3.1.2 on 2020-11-18 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20201111_1648'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wordquestion',
            options={'verbose_name': 'Word操作题目', 'verbose_name_plural': 'Word操作题目'},
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='font_color',
            field=models.CharField(blank=True, choices=[('C00000', '深红'), ('FF0000', '红色'), ('92D050', '浅绿'), ('00B050', '绿色'), ('00B0F0', '浅蓝'), ('0070C0', '蓝色'), ('7030A0', '紫色')], default='', max_length=200, verbose_name='字色(标准色)'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='font_name_ascii',
            field=models.CharField(blank=True, choices=[('Arial Black', 'Arial Black'), ('Bahnschrift', 'Bahnschrift'), ('Book Antiqua', 'Book Antiqua'), ('Dubai', 'Dubai'), ('Impact', 'Impact')], default='', max_length=200, verbose_name='英文字体'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='font_name_chinese',
            field=models.CharField(blank=True, choices=[('黑体', '黑体'), ('华文仿宋', '华文仿宋'), ('楷体', '楷体'), ('幼圆', '幼圆'), ('微软雅黑', '微软雅黑'), ('隶书', '隶书')], default='', max_length=200, verbose_name='中文字体'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='font_size',
            field=models.CharField(blank=True, choices=[('5', '5'), ('8', '8'), ('14', '14'), ('18', '18'), ('22', '22'), ('26', '26'), ('36', '36'), ('48', '48'), ('72', '72')], default='', max_length=200, verbose_name='字号(磅)'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='style_font_color',
            field=models.CharField(blank=True, choices=[('C00000', '深红'), ('FF0000', '红色'), ('92D050', '浅绿'), ('00B050', '绿色'), ('00B0F0', '浅蓝'), ('0070C0', '蓝色'), ('7030A0', '紫色')], default='', max_length=200, verbose_name='字色(标准色)'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='style_font_name_ascii',
            field=models.CharField(blank=True, choices=[('Arial Black', 'Arial Black'), ('Bahnschrift', 'Bahnschrift'), ('Book Antiqua', 'Book Antiqua'), ('Dubai', 'Dubai'), ('Impact', 'Impact')], default='', max_length=200, verbose_name='英文字体'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='style_font_name_chinese',
            field=models.CharField(blank=True, choices=[('黑体', '黑体'), ('华文仿宋', '华文仿宋'), ('楷体', '楷体'), ('幼圆', '幼圆'), ('微软雅黑', '微软雅黑'), ('隶书', '隶书')], default='', max_length=200, verbose_name='中文字体'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='style_font_size',
            field=models.CharField(blank=True, choices=[('5', '5'), ('8', '8'), ('14', '14'), ('18', '18'), ('22', '22'), ('26', '26'), ('36', '36'), ('48', '48'), ('72', '72')], default='', max_length=200, verbose_name='字号'),
        ),
    ]
