# Generated by Django 3.1.2 on 2020-10-12 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20201011_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordquestion',
            name='word_operations',
        ),
        migrations.AddField(
            model_name='wordquestion',
            name='word_operation_list',
            field=models.ManyToManyField(blank=True, to='polls.WordOperations'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='char_edit_op',
            field=models.BooleanField(blank=True, verbose_name='是否考查文字查找替换？'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='char_edit_origin',
            field=models.CharField(blank=True, max_length=200, verbose_name='原词'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='char_edit_replace',
            field=models.CharField(blank=True, max_length=200, verbose_name='替换为'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='font_bold',
            field=models.BooleanField(blank=True, verbose_name='粗体'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='font_color',
            field=models.CharField(blank=True, choices=[('无', '无'), ('红色', '红色'), ('黄色', '黄色'), ('绿色', '绿色')], max_length=200, verbose_name='字体颜色'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='font_italic',
            field=models.BooleanField(blank=True, verbose_name='斜体'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='font_name_ascii',
            field=models.CharField(blank=True, choices=[('无', '无'), ('MS Gothic', 'MS Gothic'), ('MS Mincho', 'MS Mincho'), ('MS PMincho', 'MS PMincho'), ('MS UI Gothic', 'MS UI Gothic'), ('Yu Gothic', 'Yu Gothic')], max_length=200, verbose_name='英文字体'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='font_name_chinese',
            field=models.CharField(blank=True, choices=[('无', '无'), ('宋体', '宋体'), ('黑体', '黑体'), ('华文仿宋', '华文仿宋')], max_length=200, verbose_name='中文字体'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='font_op',
            field=models.BooleanField(blank=True, verbose_name='是否考查字体设置？'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='font_size',
            field=models.CharField(blank=True, choices=[('一号', '一号'), ('二号', '二号'), ('三号', '三号'), ('四号', '四号'), ('五号', '五号'), ('六号', '六号'), ('七号', '七号'), ('八号', '八号')], max_length=200, verbose_name='字号'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='font_underline',
            field=models.CharField(blank=True, choices=[('无', '无'), ('下划线', '下划线'), ('双下划线', '双下划线'), ('粗线', '粗线')], max_length=200, verbose_name='下划线'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='keep_together',
            field=models.BooleanField(blank=True, default=False, verbose_name='段中不分页'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='keep_with_next',
            field=models.BooleanField(blank=True, default=False, verbose_name='与下段同页'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='page_break_before',
            field=models.BooleanField(blank=True, default=False, verbose_name='段前分页'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='para_alignment',
            field=models.CharField(blank=True, choices=[('无', '无'), ('左对齐', '左对齐'), ('居中', '居中'), ('右对齐', '右对齐'), ('两端对齐', '两端对齐'), ('分散对齐', '分散对齐')], max_length=200, verbose_name='段落对齐'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='para_first_line_indent',
            field=models.CharField(blank=True, choices=[('无', '无'), ('首行', '首行'), ('悬挂', '悬挂')], max_length=200, verbose_name='首行缩进'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='para_first_line_indent_size',
            field=models.DecimalField(blank=True, decimal_places=1, default=10.0, max_digits=3, verbose_name='首行缩进距离(磅)'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='para_firstchardropcap',
            field=models.CharField(blank=True, choices=[('无', '无'), ('下沉', '下沉'), ('下沉', '悬挂')], max_length=200, verbose_name='首字下沉'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='para_firstchardropcaplines',
            field=models.DecimalField(blank=True, decimal_places=1, default=3.0, max_digits=3, verbose_name='下沉(行)'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='para_left_indent',
            field=models.DecimalField(blank=True, decimal_places=1, default=10.0, max_digits=3, verbose_name='左侧缩进(磅)'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='para_line_page',
            field=models.BooleanField(blank=True, default=False, verbose_name='是否考查分页设置？'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='para_line_spacing',
            field=models.DecimalField(blank=True, decimal_places=1, default=1.0, max_digits=3, verbose_name='行距(行)'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='para_line_spacing_rule',
            field=models.CharField(blank=True, choices=[('无', '无'), ('单倍行距', '单倍行距'), ('多倍行距', '多倍行距'), ('固定值', '固定值')], max_length=200, verbose_name='行距规则'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='para_right_indent',
            field=models.DecimalField(blank=True, decimal_places=1, default=10.0, max_digits=3, verbose_name='右侧缩进(磅)'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='para_space_after',
            field=models.DecimalField(blank=True, decimal_places=1, default=10.0, max_digits=3, verbose_name='段后间距(磅)'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='para_space_before',
            field=models.DecimalField(blank=True, decimal_places=1, default=10.0, max_digits=3, verbose_name='段前间距(磅)'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='para_text',
            field=models.TextField(max_length=2000, verbose_name='要考查的段落内容'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='paraformat_op',
            field=models.BooleanField(blank=True, verbose_name='是否考查段落格式设置？'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='pub_date',
            field=models.DateTimeField(verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='window_control',
            field=models.BooleanField(blank=True, default=False, verbose_name='孤行控制'),
        ),
        migrations.AlterField(
            model_name='wordquestion',
            name='pub_date',
            field=models.DateTimeField(verbose_name='创建时间'),
        ),
    ]
