# Generated by Django 3.1.2 on 2020-12-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_exampaper_current_choice_question_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampaper',
            name='student_id',
            field=models.CharField(default='', max_length=20, verbose_name='学号'),
        ),
    ]
