# Generated by Django 3.1.2 on 2020-11-18 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20201118_0929'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='题干')),
                ('choice_1', models.CharField(default='', max_length=200, verbose_name='选项1')),
                ('choice_2', models.CharField(default='', max_length=200, verbose_name='选项2')),
                ('choice_3', models.CharField(default='', max_length=200, verbose_name='选项3')),
                ('choice_4', models.CharField(default='', max_length=200, verbose_name='选项4')),
                ('answer', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=2, verbose_name='答案')),
            ],
            options={
                'verbose_name': '选择题',
                'verbose_name_plural': '选择题',
            },
        ),
    ]
