# Generated by Django 3.1.2 on 2020-11-18 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_choicequestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordoperations',
            name='table_alignment',
            field=models.CharField(choices=[('', '左对齐'), ('', '居中'), ('', '右对齐')], default='', max_length=10, verbose_name='对齐方式'),
        ),
        migrations.AddField(
            model_name='wordoperations',
            name='table_autofit',
            field=models.BooleanField(default=False, verbose_name='表格宽度自动调整？'),
        ),
        migrations.AddField(
            model_name='wordoperations',
            name='table_op',
            field=models.BooleanField(default=False, verbose_name='考查表格插入？'),
        ),
        migrations.AddField(
            model_name='wordoperations',
            name='table_style',
            field=models.CharField(choices=[('', '左对齐'), ('', '居中'), ('', '右对齐')], default='', max_length=30, verbose_name='表格样式'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='char_edit_op',
            field=models.BooleanField(default=False, verbose_name='考查文字查找替换？'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='font_op',
            field=models.BooleanField(default=False, verbose_name='考查字体设置？'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='image_op',
            field=models.BooleanField(default=False, verbose_name='考查图片插入？'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='image_position_style',
            field=models.CharField(choices=[('嵌入文本行中', '嵌入文本行中')], default='嵌入文本行中', max_length=20, verbose_name='位置类型'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='paraformat_op',
            field=models.BooleanField(default=False, verbose_name='考查段落格式设置？'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='style_op',
            field=models.BooleanField(default=False, verbose_name='考查样式设置？'),
        ),
    ]
