# Generated by Django 3.1.2 on 2020-10-14 00:41

from django.db import migrations, models
import django.db.models.deletion
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_wordquestion_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordDocxFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(blank=True, null=True, upload_to='uploads_docx/', validators=[polls.models.validate_docx])),
            ],
        ),
        migrations.AlterField(
            model_name='wordquestion',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='uploads_docx/', validators=[polls.models.validate_docx]),
        ),
        migrations.AddField(
            model_name='wordquestion',
            name='upload_word',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.worddocxfile'),
        ),
    ]
