# Generated by Django 3.1.2 on 2020-10-14 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20201014_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordquestion',
            name='upload_word',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.worddocxfile', verbose_name='测试文件.docx'),
        ),
        migrations.AlterField(
            model_name='wordquestion',
            name='word_operation_list',
            field=models.ManyToManyField(blank=True, to='polls.WordOperations', verbose_name='操作题目列表'),
        ),
    ]
