# Generated by Django 3.1.2 on 2020-11-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20201130_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='创建时间')),
                ('exam_name', models.CharField(max_length=50, verbose_name='考场名称')),
                ('exam_type', models.CharField(choices=[('计算机等级考试一', '计算机等级考试一')], max_length=50, verbose_name='考试类型')),
            ],
            options={
                'verbose_name': '考试信息',
                'verbose_name_plural': '考试信息',
            },
        ),
    ]
