# Generated by Django 3.1.2 on 2020-10-14 01:05

from django.db import migrations, models
import django.db.models.deletion
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20201014_0855'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordDocxFileTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(blank=True, null=True, upload_to='uploads_docx/', validators=[polls.models.validate_docx])),
            ],
        ),
        migrations.RemoveField(
            model_name='wordquestion',
            name='upload',
        ),
        migrations.RemoveField(
            model_name='wordquestion',
            name='upload_word',
        ),
        migrations.AddField(
            model_name='wordquestion',
            name='upload_docx',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.worddocxfile', verbose_name='原始Word文件(.docx)'),
        ),
        migrations.AddField(
            model_name='wordquestion',
            name='upload_docx_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.worddocxfiletest', verbose_name='测试word文件.docx'),
        ),
    ]
