# Generated by Django 3.1.2 on 2020-10-21 00:42

from django.db import migrations, models
import django.db.models.deletion
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20201014_0905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worddocxfile',
            options={'verbose_name': '考试用Word文件', 'verbose_name_plural': '考试用Word文件'},
        ),
        migrations.AlterModelOptions(
            name='worddocxfiletest',
            options={'verbose_name': '内部测试用word文件', 'verbose_name_plural': '内部测试用word文件'},
        ),
        migrations.AlterModelOptions(
            name='wordoperations',
            options={'verbose_name': 'Word操作', 'verbose_name_plural': 'Word操作'},
        ),
        migrations.AlterModelOptions(
            name='wordquestion',
            options={'verbose_name': 'Word题目', 'verbose_name_plural': 'Word题目'},
        ),
        migrations.RemoveField(
            model_name='wordoperations',
            name='para_line_page',
        ),
        migrations.AddField(
            model_name='wordoperations',
            name='style_font_bold',
            field=models.BooleanField(blank=True, null=True, verbose_name='粗体'),
        ),
        migrations.AddField(
            model_name='wordoperations',
            name='style_font_color',
            field=models.CharField(blank=True, choices=[('无', '无'), ('红色', '红色'), ('黄色', '黄色'), ('绿色', '绿色')], max_length=200, verbose_name='字体颜色'),
        ),
        migrations.AddField(
            model_name='wordoperations',
            name='style_font_italic',
            field=models.BooleanField(blank=True, null=True, verbose_name='斜体'),
        ),
        migrations.AddField(
            model_name='wordoperations',
            name='style_font_name_ascii',
            field=models.CharField(blank=True, choices=[('无', '无'), ('MS Gothic', 'MS Gothic'), ('MS Mincho', 'MS Mincho'), ('MS PMincho', 'MS PMincho'), ('MS UI Gothic', 'MS UI Gothic'), ('Yu Gothic', 'Yu Gothic')], max_length=200, verbose_name='英文字体'),
        ),
        migrations.AddField(
            model_name='wordoperations',
            name='style_font_name_chinese',
            field=models.CharField(blank=True, choices=[('无', '无'), ('宋体', '宋体'), ('黑体', '黑体'), ('华文仿宋', '华文仿宋')], max_length=200, verbose_name='中文字体'),
        ),
        migrations.AddField(
            model_name='wordoperations',
            name='style_font_size',
            field=models.CharField(blank=True, choices=[('一号', '一号'), ('二号', '二号'), ('三号', '三号'), ('四号', '四号'), ('五号', '五号'), ('六号', '六号'), ('七号', '七号'), ('八号', '八号')], max_length=200, verbose_name='字号'),
        ),
        migrations.AddField(
            model_name='wordoperations',
            name='style_font_underline',
            field=models.CharField(blank=True, choices=[('无', '无'), ('下划线', '下划线'), ('双下划线', '双下划线'), ('粗线', '粗线')], max_length=200, verbose_name='下划线'),
        ),
        migrations.AddField(
            model_name='wordoperations',
            name='style_op',
            field=models.BooleanField(blank=True, null=True, verbose_name='是否考样式设置？'),
        ),
        migrations.AlterField(
            model_name='worddocxfiletest',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='uploads_docx_test/', validators=[polls.models.validate_docx]),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='char_edit_op',
            field=models.BooleanField(blank=True, null=True, verbose_name='是否考查文字查找替换？'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='font_op',
            field=models.BooleanField(blank=True, null=True, verbose_name='是否考查字体设置？'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='para_text',
            field=models.TextField(verbose_name='要考查的段落内容'),
        ),
        migrations.AlterField(
            model_name='wordoperations',
            name='paraformat_op',
            field=models.BooleanField(blank=True, null=True, verbose_name='是否考查段落格式设置？'),
        ),
        migrations.AlterField(
            model_name='wordquestion',
            name='upload_docx',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.worddocxfile', verbose_name='考试用Word文件(.docx)'),
        ),
        migrations.AlterField(
            model_name='wordquestion',
            name='upload_docx_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.worddocxfiletest', verbose_name='内部测试用word文件.docx'),
        ),
        migrations.AlterField(
            model_name='wordquestion',
            name='word_operation_list',
            field=models.ManyToManyField(blank=True, to='polls.WordOperations', verbose_name='操作题目'),
        ),
    ]
