# Generated by Django 3.1.2 on 2020-12-02 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20201130_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('计算机等级考试一', '计算机等级考试一')], max_length=50, verbose_name='考试类型')),
            ],
            options={
                'verbose_name': '试卷',
                'verbose_name_plural': '试卷',
            },
        ),
        migrations.AlterField(
            model_name='student',
            name='exam_info',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='polls.exam', verbose_name='考试编号(考试登录时填写)'),
        ),
    ]
