# Generated by Django 3.1.2 on 2020-12-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20201202_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampaper',
            name='choicequestion_list',
            field=models.CharField(default='', max_length=200, verbose_name='选择题'),
        ),
        migrations.AddField(
            model_name='exampaper',
            name='excelquestion_id',
            field=models.PositiveIntegerField(default=0, verbose_name='excel操作题'),
        ),
        migrations.AddField(
            model_name='exampaper',
            name='internetquestion_id',
            field=models.PositiveIntegerField(default=0, verbose_name='上网题'),
        ),
        migrations.AddField(
            model_name='exampaper',
            name='pptquestion_id',
            field=models.PositiveIntegerField(default=0, verbose_name='ppt操作题'),
        ),
        migrations.AddField(
            model_name='exampaper',
            name='systemquestion_id',
            field=models.PositiveIntegerField(default=0, verbose_name='系统操作题'),
        ),
        migrations.AddField(
            model_name='exampaper',
            name='wordquestion_id',
            field=models.PositiveIntegerField(default=0, verbose_name='word操作题'),
        ),
    ]
